// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
  user_id,
  request_hash,
  job_id,
  method,
  path,
  response_payload,
  status_code,
  expires_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id, user_id, request_hash, job_id, method, path, response_payload, status_code, created_at, expires_at
`

type CreateIdempotencyKeyParams struct {
	UserID          uuid.UUID
	RequestHash     string
	JobID           pgtype.UUID
	Method          string
	Path            string
	ResponsePayload []byte
	StatusCode      pgtype.Int4
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.UserID,
		arg.RequestHash,
		arg.JobID,
		arg.Method,
		arg.Path,
		arg.ResponsePayload,
		arg.StatusCode,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestHash,
		&i.JobID,
		&i.Method,
		&i.Path,
		&i.ResponsePayload,
		&i.StatusCode,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE id = $1
`

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, id)
	return err
}

const getIdempotencyKeyByHash = `-- name: GetIdempotencyKeyByHash :one
SELECT id, user_id, request_hash, job_id, method, path, response_payload, status_code, created_at, expires_at FROM idempotency_keys WHERE user_id = $1 AND request_hash = $2
`

type GetIdempotencyKeyByHashParams struct {
	UserID      uuid.UUID
	RequestHash string
}

func (q *Queries) GetIdempotencyKeyByHash(ctx context.Context, arg GetIdempotencyKeyByHashParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKeyByHash, arg.UserID, arg.RequestHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestHash,
		&i.JobID,
		&i.Method,
		&i.Path,
		&i.ResponsePayload,
		&i.StatusCode,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateIdempotencyKeyResponse = `-- name: UpdateIdempotencyKeyResponse :one
UPDATE idempotency_keys SET
  response_payload = COALESCE($1, response_payload),
  status_code = COALESCE($2, status_code),
  updated_at = now()
WHERE id = $3
RETURNING id, user_id, request_hash, job_id, method, path, response_payload, status_code, created_at, expires_at
`

type UpdateIdempotencyKeyResponseParams struct {
	ResponsePayload []byte
	StatusCode      pgtype.Int4
	ID              uuid.UUID
}

func (q *Queries) UpdateIdempotencyKeyResponse(ctx context.Context, arg UpdateIdempotencyKeyResponseParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, updateIdempotencyKeyResponse, arg.ResponsePayload, arg.StatusCode, arg.ID)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestHash,
		&i.JobID,
		&i.Method,
		&i.Path,
		&i.ResponsePayload,
		&i.StatusCode,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
