// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  user_id,
  type,
  name,
  webhook_url,
  payload,
  state,
  max_retries,
  attempts,
  scheduled_at,
  last_error,
  result
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
)
RETURNING id, user_id, type, name, webhook_url, payload, state, max_retries, attempts, scheduled_at, last_error, result, created_at, updated_at, version, timeout_seconds
`

type CreateJobParams struct {
	UserID      uuid.UUID
	Type        string
	Name        string
	WebhookUrl  string
	Payload     []byte
	State       string
	MaxRetries  int32
	Attempts    int32
	ScheduledAt pgtype.Timestamptz
	LastError   pgtype.Text
	Result      []byte
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.WebhookUrl,
		arg.Payload,
		arg.State,
		arg.MaxRetries,
		arg.Attempts,
		arg.ScheduledAt,
		arg.LastError,
		arg.Result,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.WebhookUrl,
		&i.Payload,
		&i.State,
		&i.MaxRetries,
		&i.Attempts,
		&i.ScheduledAt,
		&i.LastError,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.TimeoutSeconds,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, user_id, type, name, webhook_url, payload, state, max_retries, attempts, scheduled_at, last_error, result, created_at, updated_at, version, timeout_seconds FROM jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.WebhookUrl,
		&i.Payload,
		&i.State,
		&i.MaxRetries,
		&i.Attempts,
		&i.ScheduledAt,
		&i.LastError,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.TimeoutSeconds,
	)
	return i, err
}

const listJobsByUserID = `-- name: ListJobsByUserID :many
SELECT id, user_id, type, name, webhook_url, payload, state, max_retries, attempts, scheduled_at, last_error, result, created_at, updated_at, version, timeout_seconds FROM jobs WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListJobsByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListJobsByUserID(ctx context.Context, arg ListJobsByUserIDParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.WebhookUrl,
			&i.Payload,
			&i.State,
			&i.MaxRetries,
			&i.Attempts,
			&i.ScheduledAt,
			&i.LastError,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.TimeoutSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs SET
  type = COALESCE($1, type),
  name = COALESCE($2, name),
  webhook_url = COALESCE($3, webhook_url),
  payload = COALESCE($4, payload),
  state = COALESCE($5, state),
  max_retries = COALESCE($6, max_retries),
  attempts = COALESCE($7, attempts),
  scheduled_at = COALESCE($8, scheduled_at),
  last_error = COALESCE($9, last_error),
  result = COALESCE($10, result),
  updated_at = now()
WHERE id = $11
RETURNING id, user_id, type, name, webhook_url, payload, state, max_retries, attempts, scheduled_at, last_error, result, created_at, updated_at, version, timeout_seconds
`

type UpdateJobParams struct {
	Type        string
	Name        string
	WebhookUrl  string
	Payload     []byte
	State       string
	MaxRetries  int32
	Attempts    int32
	ScheduledAt pgtype.Timestamptz
	LastError   pgtype.Text
	Result      []byte
	ID          uuid.UUID
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.Type,
		arg.Name,
		arg.WebhookUrl,
		arg.Payload,
		arg.State,
		arg.MaxRetries,
		arg.Attempts,
		arg.ScheduledAt,
		arg.LastError,
		arg.Result,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.WebhookUrl,
		&i.Payload,
		&i.State,
		&i.MaxRetries,
		&i.Attempts,
		&i.ScheduledAt,
		&i.LastError,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.TimeoutSeconds,
	)
	return i, err
}
