// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyKey struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	RequestHash     string
	JobID           pgtype.UUID
	Method          string
	Path            string
	ResponsePayload []byte
	StatusCode      pgtype.Int4
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

type Job struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Type           string
	Name           string
	WebhookUrl     string
	Payload        []byte
	State          string
	MaxRetries     int32
	Attempts       int32
	ScheduledAt    pgtype.Timestamptz
	LastError      pgtype.Text
	Result         []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Version        int32
	TimeoutSeconds int32
}

type Outbox struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	Published     bool
	PublishedAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	ID                       uuid.UUID
	Username                 pgtype.Text
	Email                    string
	PasswordHash             string
	KeycloakID               pgtype.Text
	KeycloakAccessToken      pgtype.Text
	KeycloakRefreshToken     pgtype.Text
	KeycloakAccessExpiresAt  pgtype.Timestamptz
	KeycloakRefreshExpiresAt pgtype.Timestamptz
	IsActive                 bool
	Roles                    []string
	Metadata                 []byte
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}
