// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox (
  aggregate_type,
  aggregate_id,
  event_type,
  payload,
  published
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, aggregate_type, aggregate_id, event_type, payload, published, published_at, created_at, updated_at
`

type CreateOutboxEventParams struct {
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	Published     bool
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Published,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Published,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOutboxEvent = `-- name: DeleteOutboxEvent :exec
DELETE FROM outbox WHERE id = $1
`

func (q *Queries) DeleteOutboxEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOutboxEvent, id)
	return err
}

const getUnpublishedOutboxEvents = `-- name: GetUnpublishedOutboxEvents :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, published, published_at, created_at, updated_at FROM outbox WHERE published = false ORDER BY created_at ASC LIMIT $1 FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Published,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :one
UPDATE outbox SET published = true, published_at = now(), updated_at = now() WHERE id = $1 RETURNING id, aggregate_type, aggregate_id, event_type, payload, published, published_at, created_at, updated_at
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) (Outbox, error) {
	row := q.db.QueryRow(ctx, markOutboxEventPublished, id)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Published,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
