// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  email,
  password_hash,
  keycloak_id,
  keycloak_access_token,
  keycloak_refresh_token,
  keycloak_access_expires_at,
  keycloak_refresh_expires_at,
  is_active,
  roles,
  metadata
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
)
RETURNING id, username, email, password_hash, keycloak_id, keycloak_access_token, keycloak_refresh_token, keycloak_access_expires_at, keycloak_refresh_expires_at, is_active, roles, metadata, created_at, updated_at
`

type CreateUserParams struct {
	Username                 pgtype.Text
	Email                    string
	PasswordHash             string
	KeycloakID               pgtype.Text
	KeycloakAccessToken      pgtype.Text
	KeycloakRefreshToken     pgtype.Text
	KeycloakAccessExpiresAt  pgtype.Timestamptz
	KeycloakRefreshExpiresAt pgtype.Timestamptz
	IsActive                 bool
	Roles                    []string
	Metadata                 []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.KeycloakID,
		arg.KeycloakAccessToken,
		arg.KeycloakRefreshToken,
		arg.KeycloakAccessExpiresAt,
		arg.KeycloakRefreshExpiresAt,
		arg.IsActive,
		arg.Roles,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.KeycloakID,
		&i.KeycloakAccessToken,
		&i.KeycloakRefreshToken,
		&i.KeycloakAccessExpiresAt,
		&i.KeycloakRefreshExpiresAt,
		&i.IsActive,
		&i.Roles,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, keycloak_id, keycloak_access_token, keycloak_refresh_token, keycloak_access_expires_at, keycloak_refresh_expires_at, is_active, roles, metadata, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.KeycloakID,
		&i.KeycloakAccessToken,
		&i.KeycloakRefreshToken,
		&i.KeycloakAccessExpiresAt,
		&i.KeycloakRefreshExpiresAt,
		&i.IsActive,
		&i.Roles,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, keycloak_id, keycloak_access_token, keycloak_refresh_token, keycloak_access_expires_at, keycloak_refresh_expires_at, is_active, roles, metadata, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.KeycloakID,
		&i.KeycloakAccessToken,
		&i.KeycloakRefreshToken,
		&i.KeycloakAccessExpiresAt,
		&i.KeycloakRefreshExpiresAt,
		&i.IsActive,
		&i.Roles,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByKeycloakID = `-- name: GetUserByKeycloakID :one
SELECT id, username, email, password_hash, keycloak_id, keycloak_access_token, keycloak_refresh_token, keycloak_access_expires_at, keycloak_refresh_expires_at, is_active, roles, metadata, created_at, updated_at FROM users WHERE keycloak_id = $1
`

func (q *Queries) GetUserByKeycloakID(ctx context.Context, keycloakID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByKeycloakID, keycloakID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.KeycloakID,
		&i.KeycloakAccessToken,
		&i.KeycloakRefreshToken,
		&i.KeycloakAccessExpiresAt,
		&i.KeycloakRefreshExpiresAt,
		&i.IsActive,
		&i.Roles,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  username = COALESCE($1, username),
  email = COALESCE($2, email),
  password_hash = COALESCE($3, password_hash),
  keycloak_id = COALESCE($4, keycloak_id),
  keycloak_access_token = COALESCE($5, keycloak_access_token),
  keycloak_refresh_token = COALESCE($6, keycloak_refresh_token),
  keycloak_access_expires_at = COALESCE($7, keycloak_access_expires_at),
  keycloak_refresh_expires_at = COALESCE($8, keycloak_refresh_expires_at),
  is_active = COALESCE($9, is_active),
  roles = COALESCE($10, roles),
  metadata = COALESCE($11, metadata),
  updated_at = now()
WHERE id = $12
RETURNING id, username, email, password_hash, keycloak_id, keycloak_access_token, keycloak_refresh_token, keycloak_access_expires_at, keycloak_refresh_expires_at, is_active, roles, metadata, created_at, updated_at
`

type UpdateUserParams struct {
	Username                 pgtype.Text
	Email                    string
	PasswordHash             string
	KeycloakID               pgtype.Text
	KeycloakAccessToken      pgtype.Text
	KeycloakRefreshToken     pgtype.Text
	KeycloakAccessExpiresAt  pgtype.Timestamptz
	KeycloakRefreshExpiresAt pgtype.Timestamptz
	IsActive                 bool
	Roles                    []string
	Metadata                 []byte
	ID                       uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.KeycloakID,
		arg.KeycloakAccessToken,
		arg.KeycloakRefreshToken,
		arg.KeycloakAccessExpiresAt,
		arg.KeycloakRefreshExpiresAt,
		arg.IsActive,
		arg.Roles,
		arg.Metadata,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.KeycloakID,
		&i.KeycloakAccessToken,
		&i.KeycloakRefreshToken,
		&i.KeycloakAccessExpiresAt,
		&i.KeycloakRefreshExpiresAt,
		&i.IsActive,
		&i.Roles,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
